### ISSUE TITLE
Cook?

### ISSUE THREAD

**Issue by shakna-israel** [janet-lang/circlet#1]
I'm using Janet 1.0.0-dev-232ea22 from janet-lang-git on the AUR.

Unfortunately build won't run because Janet doesn't know where cook is.

... Any idea where I can find this dependency?

**Comment by bakpakin** [comment]
You can install it with the git installer. It seems like the AUR package doesn't install the handful of built-in modules, including cook.

```sh
git clone https://github.com/janet-lang/janet
cd janet
make -j 12
sudo make install
```

**Comment by pdobsan** [comment]
> It seems like the AUR package doesn't install the handful of built-in modules,

Actually the modules were installed but the search path built in was wrong.
Anyway this module loading problem is now solved on ArchLinux,

Just reinstall the `janet-lang-git` package from AUR.

**Comment by bakpakin** [comment]
Nice, closing.
