### ISSUE TITLE
Problem building with new mongoose

### ISSUE THREAD

**Issue by saikyun** [janet-lang/circlet#14]
I wanted to try wrapping the websocket stuff, so I looked at a mongoose example: https://github.com/cesanta/mongoose/tree/master/examples/websocket-server

It needs latest mongoose though, so I tried `jpm run update-mongoose`. However, now `jpm build` is unable to build mongoose.
It appears as though some required files aren't included (e.g. `time.h` and `limit.h`). I could resolve this by hard coding includes for these, but I don't need to do that if I compile mongoose manually using gcc (without jpm build that is), so I'm unsure about what's going on.

I'm on Ubuntu, Janet 1.17.1-b799223e and jpm c2be9143201154c2b068f954474f1e0983f81189.

Here's the errors I get after running update-mongoose then jpm build. I understand that I get circlet-errors, it's the ones relating to mongoose.h I'm confused about: https://pastebin.com/6fzA15w6

**Comment by saikyun** [comment]
After using `jpm --verbose build` (thanks @sogaiu), I figured out that jpm adds `-std=c99` that mongoose doesn't like for some reason. Seems a bit odd to me. Will investigate a bit more.

**Comment by saikyun** [comment]
After thinking about various alternatives, it seems like the easiest path is to just wrap the websocket functions that exist in the version of mongoose working with circlet today. Closing for now. :)

**Comment by pepe** [comment]
Just FYI, part of the GoodPlace is https://git.sr.ht/~pepe/trevor as a websockets handler.

**Comment by saikyun** [comment]
Thanks. :) I tried it and had some trouble installing dependency leveldb.
So decided to implement it in circlet.

Den ons 15 sep. 2021 14:56Josef Pospíšil ***@***.***> skrev:

**Comment by pepe** [comment]
LevelDB? You are talking about chidi, and like year ago :-D. But np.

**Comment by saikyun** [comment]
Iiuc Trevor depends on chidi, or? Not sure how to use it otherwise. :)

Den ons 15 sep. 2021 17:19Josef Pospíšil ***@***.***> skrev:

**Comment by pepe** [comment]
It uses its server part, but even chidi does not depend on LevelDB. Anyway no hard feelings here :)

**Comment by saikyun** [comment]
Of course there are no hard feelings, I'm just trying to give you feedback. :) I'll make an issue in Chidi instead: https://github.com/good-place/chidi/issues/7
