### ISSUE TITLE
Default the network interface to `localhost` otherwise specify it

### ISSUE THREAD

**Issue by pdobsan** [janet-lang/circlet#2]
Currently `circlet/server` takes only a `port` parameter and binds to all available interfaces behind the scenes. The caller has no control over what interface(s) to bind to. I believe that this is not a good design and causes certain security risks. Any network server should bind to `localhost` only as a default and make the interface explicitly controllable if desired otherwise.

I propose a modification with the following semantics:

    (server 8000)                 ==> Circlet server listening on [localhost:8000] ...

    (server 8000 "localhost")     ==> Circlet server listening on [localhost:8000] ...

    (server 8000 "192.168.1.130") ==> Circlet server listening on [192.168.1.130:8000] ...

    (server 8000 "*")             ==> Circlet server listening on [*:8000] ... (all interfaces)

Fortunately the necessary changes are minimal and can be done on high level in `circlet_lib.janet`:

```diff
diff --git a/circlet_lib.janet b/circlet_lib.janet
index 52b3d0e..23fe61d 100644
--- a/circlet_lib.janet
+++ b/circlet_lib.janet
@@ -35,13 +35,18 @@
 
 (defn server 
   "Creates a simple http server"
-  [port handler]
+  [handler port &opt ip-address]
   (def mgr (manager))
   (def mw (middleware handler))
+  (default ip-address "localhost")
+  (var interface nil)
+  (if (peg/match "*" ip-address)
+    (set interface (string port))
+    (set interface (string/format "%s:%d" ip-address port)))
   (defn evloop []
-    (print "Circlet server listening on port " port "...")
+    (print (string/format "Circlet server listening on [%s:%d] ..." ip-address port))
     (var req (yield nil))
     (while true
       (set req (yield (mw req)))))
-  (bind-http mgr (string port) evloop)
+  (bind-http mgr interface evloop)
   (while true (poll mgr 2000)))
```

**Comment by bakpakin** [comment]
This is a very valid complaint that is exactly the problem with python's http.server. @pdobsan I have applied your patch and updated the test server.
